/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_postmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext DEFAULT NULL,
  PRIMARY KEY (`meta_id`),
  KEY `post_id` (`post_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (1,1,'_wp_page_template','default');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (2,2,'_headstart_post','_hs_extra');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (3,2,'sharing_disabled','a:1:{i:0;N;}');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (4,2,'switch_like_status','a:1:{i:0;N;}');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (5,2,'_starter_page_template','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (6,2,'_hs_old_id','4');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (7,2,'_wpas_skip_all_services','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (8,2,'_publicize_pending','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (9,2,'_elasticsearch_data_sharing_indexed_on','2024-08-31 22:44:05');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (10,1,'_elasticsearch_data_sharing_indexed_on','2024-08-31 22:44:08');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (11,3,'_tft_homepage_template','pub/attar');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (12,3,'_wp_page_template','default');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (13,3,'_publicize_pending','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (14,3,'jabber_published','1725146316');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (15,5,'_tft_posts_page','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (16,5,'_publicize_pending','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (17,5,'jabber_published','1725146316');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (18,6,'_publicize_pending','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (19,3,'_elasticsearch_data_sharing_indexed_on','2024-08-31 23:18:37');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (20,5,'_elasticsearch_data_sharing_indexed_on','2024-08-31 23:18:37');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (21,1,'_elasticsearch_indexed_on','2024-08-31 22:44:04');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (22,2,'_elasticsearch_indexed_on','2024-08-31 22:39:05');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (23,5,'_elasticsearch_indexed_on','2024-08-31 23:20:39');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (24,3,'_jetpack_post_was_ever_published','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (25,5,'_jetpack_post_was_ever_published','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (26,10,'_publicize_pending','1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (27,12,'_wp_attached_file','woocommerce-placeholder.png');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (28,12,'_wp_attachment_metadata','a:6:{s:5:\"width\";i:1200;s:6:\"height\";i:1200;s:4:\"file\";s:27:\"woocommerce-placeholder.png\";s:8:\"filesize\";i:102644;s:5:\"sizes\";a:4:{s:6:\"medium\";a:5:{s:4:\"file\";s:35:\"woocommerce-placeholder-300x300.png\";s:5:\"width\";i:300;s:6:\"height\";i:300;s:9:\"mime-type\";s:9:\"image/png\";s:7:\"virtual\";b:1;}s:5:\"large\";a:5:{s:4:\"file\";s:37:\"woocommerce-placeholder-1024x1024.png\";s:5:\"width\";i:1024;s:6:\"height\";i:1024;s:9:\"mime-type\";s:9:\"image/png\";s:7:\"virtual\";b:1;}s:9:\"thumbnail\";a:5:{s:4:\"file\";s:35:\"woocommerce-placeholder-150x150.png\";s:5:\"width\";i:150;s:6:\"height\";i:150;s:9:\"mime-type\";s:9:\"image/png\";s:7:\"virtual\";b:1;}s:12:\"medium_large\";a:5:{s:4:\"file\";s:35:\"woocommerce-placeholder-768x768.png\";s:5:\"width\";i:768;s:6:\"height\";i:768;s:9:\"mime-type\";s:9:\"image/png\";s:7:\"virtual\";b:1;}}s:10:\"image_meta\";a:12:{s:8:\"aperture\";s:1:\"0\";s:6:\"credit\";s:0:\"\";s:6:\"camera\";s:0:\"\";s:7:\"caption\";s:0:\"\";s:17:\"created_timestamp\";s:1:\"0\";s:9:\"copyright\";s:0:\"\";s:12:\"focal_length\";s:1:\"0\";s:3:\"iso\";s:1:\"0\";s:13:\"shutter_speed\";s:1:\"0\";s:5:\"title\";s:0:\"\";s:11:\"orientation\";s:1:\"0\";s:8:\"keywords\";a:0:{}}}');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (29,20,'_edit_lock','1725150076:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (30,20,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (31,24,'_edit_lock','1725150885:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (32,24,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (33,25,'_created_via','post-new');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (34,25,'_last_editor_used_jetpack','classic-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (35,27,'_created_via','unknown');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (36,27,'total_sales','0');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (37,27,'_tax_status','taxable');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (38,27,'_tax_class','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (39,27,'_manage_stock','no');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (40,27,'_backorders','no');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (41,27,'_sold_individually','no');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (42,27,'_virtual','no');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (43,27,'_downloadable','no');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (44,27,'_download_limit','-1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (45,27,'_download_expiry','-1');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (46,27,'_stock',NULL);
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (47,27,'_stock_status','instock');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (48,27,'_wc_average_rating','0');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (49,27,'_wc_review_count','0');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (50,27,'_product_version','9.2.3');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (51,27,'_edit_lock','1725165380:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (52,27,'_last_editor_used_jetpack','classic-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (53,28,'_edit_lock','1725166106:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (54,28,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (55,29,'_edit_lock','1725166246:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (56,29,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (57,29,'jetpack_seo_noindex','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (58,29,'_jetpack_post_was_ever_published','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (59,29,'_starter_page_template','centered-heading-with-contact-form');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (60,29,'_wpcom_template_layout_category','a:1:{i:0;s:7:\"contact\";}');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (61,29,'footnotes','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (62,30,'footnotes','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (63,29,'_g_feedback_shortcode_fc810390a67f6dca5d417fbc74303cd5338a440d','<div class=\"wp-block-jetpack-contact-form is-style-default\">[contact-field label=\"First name\" required=\"1\" requiredText=\"(required)\" width=\"50\" borderRadius=\"5\" type=\"name\"/]\n\n[contact-field label=\"Last name\" required=\"1\" requiredText=\"(required)\" width=\"50\" borderRadius=\"5\" type=\"name\"/]\n\n[contact-field required=\"1\" requiredText=\"(required)\" borderRadius=\"5\" type=\"email\" label=\"Email\"/]\n\n[contact-field label=\"Message\" requiredText=\"(required)\" borderRadius=\"5\" type=\"textarea\"/]\n\n<div class=\"wp-block-jetpack-button aligncenter wp-block-button\" style=\"max-width: 100%\"><button class=\"wp-block-button__link\" style=\"width: ; max-width: 100%\" data-id-attr=\"placeholder\" type=\"submit\">Send</button></div></div>');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (64,29,'_g_feedback_shortcode_atts_fc810390a67f6dca5d417fbc74303cd5338a440d','a:17:{s:2:\"to\";s:0:\"\";s:7:\"subject\";s:23:\"Contact form submission\";s:12:\"show_subject\";s:2:\"no\";s:6:\"widget\";i:0;s:14:\"block_template\";N;s:19:\"block_template_part\";N;s:2:\"id\";i:29;s:18:\"submit_button_text\";s:6:\"Submit\";s:14:\"customThankyou\";s:0:\"\";s:21:\"customThankyouHeading\";s:26:\"Your message has been sent\";s:21:\"customThankyouMessage\";s:30:\"Thank you for your submission!\";s:22:\"customThankyouRedirect\";s:0:\"\";s:10:\"jetpackCRM\";b:1;s:9:\"className\";s:16:\"is-style-default\";s:9:\"postToUrl\";N;s:14:\"salesforceData\";N;s:12:\"hiddenFields\";N;}');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (65,31,'_edit_lock','1725166171:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (66,31,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (67,13,'_edit_lock','1725167391:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (68,13,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (69,1,'_edit_lock','1725228092:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (70,1,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (71,34,'_edit_lock','1725199198:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (72,34,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (73,36,'_tft_homepage_template','marl');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (74,36,'_wp_page_template','header-footer-only');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (75,40,'origin','theme');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (76,36,'_edit_lock','1725215081:255077085');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (77,36,'_last_editor_used_jetpack','block-editor');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (78,23,'_wp_trash_meta_status','draft');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (79,23,'_wp_trash_meta_time','1725392519');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (80,23,'_wp_desired_post_slug','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (81,21,'_wp_trash_meta_status','draft');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (82,21,'_wp_trash_meta_time','1725392519');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (83,21,'_wp_desired_post_slug','');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (84,22,'_wp_trash_meta_status','draft');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (85,22,'_wp_trash_meta_time','1725392519');
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES (86,22,'_wp_desired_post_slug','');
